[package]
name = "timed-tests"
version = "0.1.0"
edition = "2021"
# path = "src/lib.rs"

[workspace]
members = ["macros"]

[dependencies]
macros = {path = "macros"}
rand = "0.8.5"

[dev-dependencies]
pretty_assertions = "1.4.0"

